repos:
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.9.3
  #   hooks:
  #     # Run the linter.
  #     - id: ruff
  #       args: [ --fix, --line-length 120 ]
  #     # Run the formatter.
  #     - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
