name: Check code for Black style

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check code with black
      run: |
        black --check --diff --no-color .
